# Free GPUs for All

The purpose is to showcase the power and flexibility of Google Colab to solve a classification problem. We will be leveraging Tensorflow's Imagenet pre-trained model to complete our task.

### Setup

Importing Tensorflow

In [0]:
import tensorflow as tf

Checking version of Tensorflow

In [3]:
!pip list | grep tensorflow

DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
tensorflow (1.4.1)
tensorflow-tensorboard (0.4.0)


Ensuring GPU setup for this notebook

In [2]:
tf.test.gpu_device_name()

'/device:GPU:0'

### Download Pre-Trained Model

In [0]:
!git clone https://github.com/tensorflow/models.git

Cloning into 'models'...
remote: Counting objects: 11513, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 11513 (delta 2), reused 2 (delta 2), pack-reused 11504
Receiving objects: 100% (11513/11513), 313.91 MiB | 42.61 MiB/s, done.
Resolving deltas: 100% (6229/6229), done.


### Running Our Model

Directory where the imagenet model is located:

In [0]:
cd models/models/tutorials/image/imagenet/

/models/models/tutorials/image/imagenet


Saving a picture of a basketball to our instance. We will use this image with the pre-trained imagenet classifier.

In [0]:
!wget http://3.bp.blogspot.com/_qjlkTyHLyuw/TFt3adewwrI/AAAAAAAAAAk/Bdz2jz79Yjs/s1600/Basketball-large.png

--2018-02-07 22:47:09--  http://3.bp.blogspot.com/_qjlkTyHLyuw/TFt3adewwrI/AAAAAAAAAAk/Bdz2jz79Yjs/s1600/Basketball-large.png
Resolving 3.bp.blogspot.com (3.bp.blogspot.com)... 74.125.141.132, 2607:f8b0:400c:c06::84
Connecting to 3.bp.blogspot.com (3.bp.blogspot.com)|74.125.141.132|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 92358 (90K) [image/png]
Saving to: ‘Basketball-large.png’

Basketball-large.pn 100%[===================>]  90.19K  --.-KB/s    in 0s      

2018-02-07 22:47:09 (442 MB/s) - ‘Basketball-large.png’ saved [92358/92358]



Running pre-trained classification model on our image of a basketball

In [0]:
!python classify_image.py --image_file Basketball-large.png

/usr/local/lib/python3.6/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2018-02-07 22:47:25.031609: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:892] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-02-07 22:47:25.031962: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties: 
name: Tesla K80 major: 3 minor: 7 memoryClockRate(GHz): 0.8235
pciBusID: 0000:00:04.0
totalMemory: 11.17GiB freeMemory: 505.38MiB
2018-02-07 22:47:25.032000: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: Tesla K80, pci bus id: 0000:00:04.0, compute capability: 3.7)
2018-02-07 22:47:

### Results

Our model is 99.9% certain that our basketball image is in fact a basketball. Feel free to test the model with any image and see what you get. The imagenet model is pretrained with ~1,000 categories.

### Common Errors


If running:
```
!python classify_image.py
```
yields:

```
/usr/local/lib/python3.6/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
>> Downloading inception-2015-12-05.tgz 100.0%
Successfully downloaded inception-2015-12-05.tgz 88931400 bytes.
2018-02-07 22:06:11.433260: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:892] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-02-07 22:06:11.433505: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties: 
name: Tesla K80 major: 3 minor: 7 memoryClockRate(GHz): 0.8235
pciBusID: 0000:00:04.0
totalMemory: 11.17GiB freeMemory: 163.62MiB
2018-02-07 22:06:11.433538: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: Tesla K80, pci bus id: 0000:00:04.0, compute capability: 3.7)
2018-02-07 22:06:11.442068: E tensorflow/stream_executor/cuda/cuda_driver.cc:936] failed to allocate 163.62M (171573248 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2018-02-07 22:06:11.761083: W tensorflow/core/framework/op_def_util.cc:334] Op BatchNormWithGlobalNormalization is deprecated. It will cease to work in GraphDef version 9. Use tf.nn.batch_normalization().
2018-02-07 22:06:11.979617: E tensorflow/stream_executor/cuda/cuda_blas.cc:366] failed to create cublas handle: CUBLAS_STATUS_ALLOC_FAILED
2018-02-07 22:06:12.055508: E tensorflow/stream_executor/cuda/cuda_dnn.cc:385] could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2018-02-07 22:06:12.055596: E tensorflow/stream_executor/cuda/cuda_dnn.cc:352] could not destroy cudnn handle: CUDNN_STATUS_BAD_PARAM
2018-02-07 22:06:12.055615: F tensorflow/core/kernels/conv_ops.cc:667] Check failed: stream->parent()->GetConvolveAlgorithms( conv_parameters.ShouldIncludeWinogradNonfusedAlgo<T>(), &algorithms) 
Aborted (core dumped)
```



In [4]:
It is because of memory

SyntaxError: ignored

It is because of memory

Can run:

In [6]:
!du -hs * | sort -rh | head -5

893M	catsdogs
120K	datalab
88K	sampleSubmission.csv
4.0K	data


I just removed Python 2.7